# Generated by Django 4.2.23 on 2025-07-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('ingredients', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Veg', 'Vegetarian'), ('Non-Veg', 'Non-Vegetarian')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
