# Generated by Django 4.2.23 on 2025-08-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
