# Generated by Django 4.2.23 on 2025-08-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('delieverd', 'delieverd'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
