# Generated by Django 4.2.23 on 2025-08-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='cod', max_length=20),
            preserve_default=False,
        ),
    ]
